spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1444;databaseName=LoginDatabase;TrustServerCertificate=True
    username: sa
    password: P@ssw0rd